"""ArXiv 精细翻译默认参数（代码内置，不通过环境变量覆盖）。"""

DEFAULT_TRANSLATE_MODEL = "gpt-4o-mini"
DEFAULT_TARGET_LANGUAGE = "中文"
DEFAULT_CONCURRENCY = 16
DEFAULT_CHUNK_MAX_TOKENS = 1024
DEFAULT_MAX_CHUNKS = 1200
DEFAULT_DOWNLOAD_TIMEOUT_SEC = 60
DEFAULT_LLM_TIMEOUT_SEC = 120
DEFAULT_COMPILE_TIMEOUT_SEC = 180
DEFAULT_MAX_COMPILE_TRIES = 32
DEFAULT_COMPILE_REPAIR_BASE_WINDOW = 5
